import type { Room } from "@/types/room"
import type { Floor } from "@/types/floor"
import type { NavigationPath } from "@/types/path"
import type { ClassSchedule } from "@/types/schedule"

export const floors: Floor[] = [
  {
    id: "1",
    floorName: "Ground Floor",
    floorNumber: 0,
    description: "Saint Benedict Hall - Computer labs, PT labs, offices, and student facilities",
    mapImage: "/map/ground-floor.jpg",
    totalRooms: 11,
  },
  {
    id: "2",
    floorName: "2nd Floor",
    floorNumber: 1,
    description: "Saint Benedict Hall - Second floor classrooms and facilities",
    mapImage: "/map/2nd-floor.png",
    totalRooms: 15,
  },
  {
    id: "3",
    floorName: "3rd Floor",
    floorNumber: 2,
    description: "Saint Benedict Hall - Third floor criminology rooms and classrooms",
    mapImage: "/map/3rd-floor.png",
    totalRooms: 13,
  },
  {
    id: "4",
    floorName: "4th Floor",
    floorNumber: 3,
    description: "Saint Benedict Hall - Fourth floor classrooms, psychology laboratory, and faculty rooms",
    mapImage: "/map/4rth-floor.png",
    totalRooms: 13,
  },
  {
    id: "5",
    floorName: "5th Floor",
    floorNumber: 4,
    description: "Saint Benedict Hall - Fifth floor classrooms, computer and chemistry laboratories",
    mapImage: "/map/5th-floor.png",
    totalRooms: 13,
  },
]

export const rooms: Room[] = [
  {
    id: "1",
    roomName: "Computer Lab 1",
    roomNumber: "SBH-Cl1",
    description: "Computer Laboratory Room 1",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 360, y: 600 },
    category: "Education and Training",
    assignedFaculty: "Prof. Antonio Ebrado Jr.",
    capacity: 40,
    amenities: ["Whiteboard", "Projector", "Air Conditioning", "Chairs & Tables", "Computers"],
    isAvailable: true,
  },
  {
    id: "2",
    roomName: "Computer Lab 2",
    roomNumber: "SBH-Cl2",
    description: "Computer Laboratory Room 2",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 620, y: 600 },
    category: "Education and Training",
    assignedFaculty: "Prof. Maria Santos",
    capacity: 40,
    amenities: ["Whiteboard", "Projector", "Air Conditioning", "Chairs & Tables", "Computers"],
    isAvailable: true,
  },
  {
    id: "3",
    roomName: "Computer Lab 3",
    roomNumber: "SBH-Cl3",
    description: "Computer Laboratory Room 3",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 870, y: 600 },
    category: "Education and Training",
    assignedFaculty: "Prof. Ricardo Delos Reyes",
    capacity: 30,
    amenities: ["Whiteboard", "Projector", "Air Conditioning", "Chairs & Tables", "Computers"],
    isAvailable: true,
  },
  {
    id: "4",
    roomName: "SOCI & CO-CURICULAR OFFICE",
    roomNumber: "SBH-Soci-Co-Curricular-Office",
    description: "Student Organization and Co-Curricular Activities Office",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 848, y: 225 },
    category: "Office",
    assignedFaculty: "Ms. Angela Cruz",
    amenities: ["Workstations", "Filing Cabinets", "Air Conditioning", "Relief Goods"],
    isAvailable: true,
  },
  {
    id: "5",
    roomName: "Stock Room",
    roomNumber: "SBH-Stock-Room",
    description: "Stock Room",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 1050, y: 225 },
    category: "Stock Room",
    amenities: [],
    isAvailable: true,
  },
  {
    id: "6",
    roomName: "PT Lab 1",
    roomNumber: "SBH-PTLAB1",
    description: "Physical Therapy Laboratory Room 1",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 1200, y: 600 },
    category: "Education and Training",
    amenities: ["Workstations", "Lecture Room"],
    isAvailable: true,
  },
  {
    id: "7",
    roomName: "PT Lab 2",
    roomNumber: "SBH-PTLAB2",
    description: "Physical Therapy Laboratory Room 2",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 1700, y: 600 },
    category: "Education and Training",
    amenities: ["Workstations", "Lecture Room"],
    isAvailable: true,
  },
  {
    id: "8",
    roomName: "PWD/Gender Neutral Comfort Room",
    roomNumber: "SBH-PWD-Gender-Neutral-CR",
    description: "Comfort room for any gender and PWD",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 1150, y: 225 },
    category: "Facilities",
    isAvailable: true,
  },
  {
    id: "9",
    roomName: "Elevator",
    roomNumber: "SBH-GF-ELEVATOR",
    description: "Elevator access to upper floors",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 190, y: 225 },
    category: "Facilities",
    isAvailable: true,
  },
  {
    id: "10",
    roomName: "Computer Lab 4",
    roomNumber: "SBH-Cl4",
    description: "Computer Laboratory Room 4",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 1800, y: 225 },
    category: "Education and Training",
    amenities: ["Computers", "Lecture Room"],
    isAvailable: true,
  },
  {
    id: "11",
    roomName: "Comfort Room",
    roomNumber: "SBH-Ground-floor-Comfort-Room",
    description: "Ground Floor Comfort Room",
    floor: "Ground Floor",
    floorNumber: 0,
    coordinates: { x: 1600, y: 225 },
    category: "Facilities",
    amenities: ["Toilet and Sink"],
    isAvailable: true,
  },
  // ── 2nd Floor Rooms ──
  {
    id: "2f-1",
    roomName: "Elevator",
    roomNumber: "SBH-2F-ELEVATOR",
    description: "Elevator access between floors",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 190, y: 320 },
    category: "Navigation",
    isAvailable: true,
  },
  {
    id: "2f-2",
    roomName: "Dean's Office 1",
    roomNumber: "SBH-2F-DEAN1",
    description: "Dean's Office - Left Wing Upper",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 70, y: 840 },
    category: "Office",
    amenities: ["Workstations", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "2f-3",
    roomName: "Dean's Office 2",
    roomNumber: "SBH-2F-DEAN2",
    description: "Dean's Office - Left Wing Lower",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 200, y: 950 },
    category: "Office",
    amenities: ["Workstations", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "2f-4",
    roomName: "Conference Room",
    roomNumber: "SBH-2F-CONF",
    description: "Conference Room for meetings and presentations",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 300, y: 820 },
    category: "Conference Room",
    capacity: 20,
    amenities: ["Projector", "Whiteboard", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "2f-5",
    roomName: "Printing Room",
    roomNumber: "SBH-2F-PRINT",
    description: "Printing and document services",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 440, y: 760 },
    category: "Printing",
    amenities: ["Printers", "Photocopier"],
    isAvailable: true,
  },
  {
    id: "2f-6",
    roomName: "Pantry",
    roomNumber: "SBH-2F-PANTRY",
    description: "Staff and faculty pantry area",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 390, y: 900 },
    category: "Pantry",
    amenities: ["Microwave", "Refrigerator", "Sink"],
    isAvailable: true,
  },
  {
    id: "2f-7",
    roomName: "Library",
    roomNumber: "SBH-2F-LIB",
    description: "Second floor library and study area",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 820, y: 650 },
    category: "Library",
    capacity: 60,
    amenities: ["Study Tables", "Bookshelves", "Air Conditioning", "Wi-Fi"],
    isAvailable: true,
  },
  {
    id: "2f-8",
    roomName: "Clinic",
    roomNumber: "SBH-2F-CLINIC",
    description: "Medical clinic for students and staff",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 1250, y: 650 },
    category: "Clinic",
    amenities: ["Medical Supplies", "Beds", "First Aid"],
    isAvailable: true,
  },
  {
    id: "2f-9",
    roomName: "IT Room",
    roomNumber: "SBH-2F-IT",
    description: "IT support and server room",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 1400, y: 650 },
    category: "IT",
    amenities: ["Servers", "Networking Equipment"],
    isAvailable: true,
  },
  {
    id: "2f-10",
    roomName: "Guidance Office",
    roomNumber: "SBH-2F-GUIDANCE",
    description: "Student guidance and counseling office",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 1400, y: 830 },
    category: "Office",
    amenities: ["Workstations", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "2f-11",
    roomName: "Dean's Office 3",
    roomNumber: "SBH-2F-DEAN3",
    description: "Dean's Office - Right Wing",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 1550, y: 850 },
    category: "Office",
    amenities: ["Workstations", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "2f-12",
    roomName: "Faculty Room",
    roomNumber: "SBH-2F-FACULTY",
    description: "Faculty lounge and work area",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 1579, y: 650 },
    category: "Faculty Room",
    capacity: 30,
    amenities: ["Workstations", "Lockers", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "2f-13",
    roomName: "Computer Lab 5",
    roomNumber: "SBH-2F-CL5",
    description: "Computer Laboratory Room 5",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 1700, y: 350 },
    category: "Education and Training",
    capacity: 40,
    amenities: ["Computers", "Projector", "Air Conditioning", "Whiteboard"],
    isAvailable: true,
  },
  {
    id: "2f-14",
    roomName: "Male Comfort Room",
    roomNumber: "SBH-2F-MALE-CR",
    description: "Male comfort room",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 1500, y: 250 },
    category: "Facilities",
    amenities: ["Toilet and Sink"],
    isAvailable: true,
  },
  {
    id: "2f-15",
    roomName: "Female Comfort Room",
    roomNumber: "SBH-2F-FEMALE-CR",
    description: "Female comfort room",
    floor: "2nd Floor",
    floorNumber: 1,
    coordinates: { x: 1500, y: 400 },
    category: "Facilities",
    amenities: ["Toilet and Sink"],
    isAvailable: true,
  },
  // ── 3rd Floor Rooms ──
  {
    id: "3f-1",
    roomName: "Elevator",
    roomNumber: "SBH-3F-ELEVATOR",
    description: "Elevator access between floors",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 230, y: 400 },
    category: "Navigation",
    isAvailable: true,
  },
  {
    id: "3f-2",
    roomName: "RM 301",
    roomNumber: "SBH-3F-LR1",
    description: "Lecture Room 1 - Large classroom for lectures",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 150, y: 740 },
    category: "Education and Training",
    assignedFaculty: "Prof. Elena Garcia",
    capacity: 50,
    amenities: ["Whiteboard", "Projector", "Air Conditioning", "Chairs & Tables"],
    isAvailable: true,
  },
  {
    id: "3f-3",
    roomName: "RM 302",
    roomNumber: "SBH-3F-LR2",
    description: "Lecture Room 2 - Medium classroom for lectures",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 420, y: 690 },
    category: "Education and Training",
    assignedFaculty: "Dr. Jose Mendoza",
    capacity: 40,
    amenities: ["Whiteboard", "Projector", "Air Conditioning", "Chairs & Tables"],
    isAvailable: true,
  },
  {
    id: "3f-4",
    roomName: "Faculty Room",
    roomNumber: "SBH-3F-FR",
    description: "Faculty room and work area",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 700, y: 690 },
    category: "Faculty Room",
    assignedFaculty: "Prof. Carmen Reyes",
    capacity: 15,
    amenities: ["Workstations", "Lockers", "Air Conditioning", "Coffee Maker"],
    isAvailable: true,
  },
  {
    id: "3f-5",
    roomName: "RM 304-A",
    roomNumber: "SBH-3F-RM 304-A",
    description: "Science Laboratory for biology and chemistry",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 950, y: 690 },
    category: "Education and Training",
    assignedFaculty: "Dr. Ramon Torres",
    capacity: 30,
    amenities: ["Lab Equipment", "Microscopes", "Air Conditioning", "Safety Equipment"],
    isAvailable: true,
  },
  {
    id: "3f-6",
    roomName: "RM 304-B",
    roomNumber: "SBH-3F-RM 304-B",
    description: "Faculty lounge and break area",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 1100, y: 690 },
    category: "Faculty Room",
    capacity: 15,
    amenities: ["Sofa", "Refrigerator", "Microwave", "Coffee Maker"],
    isAvailable: true,
  },
  {
    id: "3f-7",
    roomName: "RM 305-A",
    roomNumber: "SBH-3F-RM 305-A",
    description: "Computer Laboratory Room 6",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 1270, y: 690 },
    category: "Education and Training",
    assignedFaculty: "Prof. Antonio Ebrado Jr.",
    capacity: 40,
    amenities: ["Computers", "Projector", "Air Conditioning", "Whiteboard"],
    isAvailable: true,
  },
  {
    id: "3f-8",
    roomName: "RM 305-B",
    roomNumber: "SBH-3F-RM 305-B",
    description: "Lecture Room 3 - Multimedia equipped",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 1450, y: 690 },
    category: "Education and Training",
    assignedFaculty: "Prof. Maria Santos",
    capacity: 45,
    amenities: ["Projector", "Sound System", "Air Conditioning", "Chairs & Tables"],
    isAvailable: true,
  },
  {
    id: "3f-9",
    roomName: "RM 306",
    roomNumber: "SBH-3F-RM 306",
    description: "Storage room for equipment and supplies",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 1570, y: 690 },
    category: "Stock Room",
    amenities: ["Shelving", "Cabinets"],
    isAvailable: true,
  },
  {
    id: "3f-10",
    roomName: "Faculty Room",
    roomNumber: "SBH-3F-FR2",
    description: "Faculty lounge and work area",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 1800, y: 690 },
    category: "Faculty Room",
    capacity: 15,
    amenities: ["Workstations", "Lockers", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "3f-11",
    roomName: "RM 307",
    roomNumber: "SBH-3F-RM 307",
    description: "Room 307 - Standard classroom",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 1750, y: 400 },
    category: "Education and Training",
    capacity: 40,
    amenities: ["Whiteboard", "Projector", "Air Conditioning", "Chairs & Tables"],
    isAvailable: true,
  },

  {
    id: "3f-12",
    roomName: "Male Comfort Room",
    roomNumber: "SBH-3F-MALE-CR",
    description: "Male comfort room",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 1500, y: 317 },
    category: "Facilities",
    amenities: ["Toilet and Sink"],
    isAvailable: true,
  },
  {
    id: "3f-13",
    roomName: "Female Comfort Room",
    roomNumber: "SBH-3F-FEMALE-CR",
    description: "Female comfort room",
    floor: "3rd Floor",
    floorNumber: 2,
    coordinates: { x: 1500, y: 427 },
    category: "Facilities",
    amenities: ["Toilet and Sink"],
    isAvailable: true,
  },

  // ── 4th Floor Rooms ──
  {
    id: "4f-1",
    roomName: "Elevator",
    roomNumber: "SBH-4F-ELEVATOR",
    description: "Elevator access between floors",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 180, y: 420 },
    category: "Navigation",
    isAvailable: true,
  },
  {
    id: "4f-2",
    roomName: "RM 401",
    roomNumber: "SBH-4F-LHA",
    description: "Large lecture hall for seminars and events",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 120, y: 740 },
    category: "Education and Training",
    assignedFaculty: "Dr. Jose Mendoza",
    capacity: 80,
    amenities: ["Projector", "Sound System", "Air Conditioning", "Tiered Seating"],
    isAvailable: true,
  },
  {
    id: "4f-3",
    roomName: "RM 402",
    roomNumber: "SBH-4F-RM 402",
    description: "Large lecture hall for classes",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 350, y: 740 },
    category: "Education and Training",
    assignedFaculty: "Prof. Elena Garcia",
    capacity: 70,
    amenities: ["Projector", "Sound System", "Air Conditioning", "Tiered Seating"],
    isAvailable: true,
  },
  {
    id: "4f-4",
    roomName: "RM 403",
    roomNumber: "SBH-4F-DEPT",
    description: "Department administrative office",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 570, y: 740 },
    category: "Office",
    amenities: ["Workstations", "Filing Cabinets", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "4f-5",
    roomName: "Psychology Laboratory",
    roomNumber: "SBH-4F-PSYCH",
    description: "Psychology laboratory for research and experiments",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 800, y: 740 },
    category: "Education and Training",
    capacity: 50,
    amenities: ["Lab Equipment", "Projector", "Air Conditioning", "Observation Room"],
    isAvailable: true,
  },
  {
    id: "4f-6",
    roomName: "RM 405",
    roomNumber: "SBH-4F-405",
    description: "Student and academic records storage",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 1050, y: 740 },
    category: "Office",
    amenities: ["Filing Cabinets", "Workstations", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "4f-7",
    roomName: "RM 406-A",
    roomNumber: "SBH-4F-CL7",
    description: "Computer Laboratory Room 7",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 1250, y: 740 },
    category: "Education and Training",
    assignedFaculty: "Prof. Ricardo Delos Reyes",
    capacity: 40,
    amenities: ["Computers", "Projector", "Air Conditioning", "Whiteboard"],
    isAvailable: true,
  },
  {
    id: "4f-8",
    roomName: "RM 406-B",
    roomNumber: "SBH-4F-LR5",
    description: "Lecture Room 5 - Standard classroom",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 1430, y: 740 },
    category: "Education and Training",
    capacity: 45,
    amenities: ["Whiteboard", "Projector", "Air Conditioning", "Chairs & Tables"],
    isAvailable: true,
  },
  {
    id: "4f-9",
    roomName: "RM 407-A",
    roomNumber: "SBH-4F-LR6",
    description: "Lecture Room 6 - Standard classroom",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 1630, y: 740 },
    category: "Education and Training",
    capacity: 40,
    amenities: ["Whiteboard", "Projector", "Air Conditioning", "Chairs & Tables"],
    isAvailable: true,
  },

  {
    id: "4f-10",
    roomName: "RM 407-B",
    roomNumber: "SBH-4F-RM 407-B",
    description: "Room 407-B - Standard classroom",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 1830, y: 740 },
    category: "Education and Training",
    capacity: 40,
    amenities: ["Whiteboard", "Projector", "Air Conditioning", "Chairs & Tables"],
    isAvailable: true,
  },

  {
    id: "4f-11",
    roomName: "Faculty Room",
    roomNumber: "SBH-4F-FR",
    description: "Faculty room and office area",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 1700, y: 500 },
    category: "Faculty Room",
    capacity: 20,
    amenities: ["Workstations", "Filing Cabinets", "Air Conditioning", "Coffee Maker"],
    isAvailable: true,
  },
  {
    id: "4f-12",
    roomName: "Male Comfort Room",
    roomNumber: "SBH-4F-MALE-CR",
    description: "Male comfort room",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 1500, y: 317 },
    category: "Facilities",
    amenities: ["Toilet and Sink"],
    isAvailable: true,
  },
  {
    id: "4f-13",
    roomName: "Female Comfort Room",
    roomNumber: "SBH-4F-FEMALE-CR",
    description: "Female comfort room",
    floor: "4th Floor",
    floorNumber: 3,
    coordinates: { x: 1500, y: 427 },
    category: "Facilities",
    amenities: ["Toilet and Sink"],
    isAvailable: true,
  },
  // ── 5th Floor Rooms ──
  {
    id: "5f-1",
    roomName: "Elevator",
    roomNumber: "SBH-5F-ELEVATOR",
    description: "Elevator access between floors",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 190, y: 420 },
    category: "Navigation",
    isAvailable: true,
  },
  {
    id: "5f-2",
    roomName: "RM 501",
    roomNumber: "SBH-5F-RLAB1",
    description: "Research laboratory for graduate studies",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 150, y: 740 },
    category: "Education and Training",
    assignedFaculty: "Dr. Ramon Torres",
    capacity: 20,
    amenities: ["Lab Equipment", "Computers", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "5f-3",
    roomName: "RM 502",
    roomNumber: "SBH-5F-RLAB2",
    description: "Research laboratory for thesis projects",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 360, y: 740 },
    category: "Education and Training",
    assignedFaculty: "Prof. Carmen Reyes",
    capacity: 20,
    amenities: ["Lab Equipment", "Computers", "Air Conditioning"],
    isAvailable: true,
  },
  {
    id: "5f-4",
    roomName: "RM 503",
    roomNumber: "SBH-5F-SEM1",
    description: "Seminar room for presentations and defense",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 600, y: 740 },
    category: "Education and Training",
    capacity: 30,
    amenities: ["Projector", "Whiteboard", "Air Conditioning", "Conference Table"],
    isAvailable: true,
  },
  {
    id: "5f-5",
    roomName: "RM 504",
    roomNumber: "SBH-5F-SEM2",
    description: "Seminar room for group discussions",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 820, y: 740 },
    category: "Education and Training",
    capacity: 25,
    amenities: ["Projector", "Whiteboard", "Air Conditioning", "Conference Table"],
    isAvailable: true,
  },
  {
    id: "5f-6",
    roomName: "RM 505",
    roomNumber: "SBH-5F-SERVER",
    description: "Main server room and data center",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 1050, y: 740 },
    category: "IT",
    amenities: ["Servers", "Networking Equipment", "UPS", "Cooling System"],
    isAvailable: true,
  },
  {
    id: "5f-7",
    roomName: "RM 506-A",
    roomNumber: "SBH-5F-CL8",
    description: "Computer Laboratory Room 8 - Advanced computing",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 1250, y: 740 },
    category: "Education and Training",
    assignedFaculty: "Prof. Antonio Ebrado Jr.",
    capacity: 35,
    amenities: ["High-end Computers", "Projector", "Air Conditioning", "Whiteboard"],
    isAvailable: true,
  },
  {
    id: "5f-8",
    roomName: "RM 506-B",
    roomNumber: "SBH-5F-THESIS",
    description: "Thesis and capstone project work area",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 1400, y: 740 },
    category: "Education and Training",
    capacity: 30,
    amenities: ["Computers", "Printers", "Air Conditioning", "Study Tables"],
    isAvailable: true,
  },
  {
    id: "5f-9",
    roomName: "RM 507-A",
    roomNumber: "SBH-5F-RM 507-A",
    description: "Room 507-A - Standard classroom",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 1550, y: 740 },
    category: "Education and Training",
    capacity: 30,
    amenities: ["Whiteboard", "Projector", "Air Conditioning", "Chairs & Tables"],
    isAvailable: true,
  },
  {
    id: "5f-10",
    roomName: "Chemistry Laboratory",
    roomNumber: "SBH-5F-CHEMLAB",
    description: "Chemistry laboratory for experiments and research",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 1750, y: 740 },
    category: "Education and Training",
    capacity: 30,
    amenities: ["Lab Equipment", "Fume Hood", "Air Conditioning", "Safety Showers"],
    isAvailable: true,
  },
  {
    id: "5f-11",
    roomName: "Computer Laboratory 5",
    roomNumber: "SBH-5F-CL5",
    description: "Computer Laboratory Room 5",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 1750, y: 400 },
    category: "Education and Training",
    capacity: 35,
    amenities: ["Computers", "Projector", "Air Conditioning", "Whiteboard"],
    isAvailable: true,
  },
  {
    id: "5f-12",
    roomName: "Male Comfort Room",
    roomNumber: "SBH-5F-MALE-CR",
    description: "Male comfort room",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 1500, y: 317 },
    category: "Facilities",
    amenities: ["Toilet and Sink"],
    isAvailable: true,
  },
  {
    id: "5f-13",
    roomName: "Female Comfort Room",
    roomNumber: "SBH-5F-FEMALE-CR",
    description: "Female comfort room",
    floor: "5th Floor",
    floorNumber: 4,
    coordinates: { x: 1500, y: 427 },
    category: "Facilities",
    amenities: ["Toilet and Sink"],
    isAvailable: true,
  },
]

export const navigationPaths: NavigationPath[] = [
  // ── Ground Floor Navigation Paths (from Elevator) ──
  {
    id: "1",
    fromRoom: "9", // Elevator
    toRoom: "1", // Computer Lab 1
    pathCoordinates: [
      { x: 190, y: 225 },
      { x: 190, y: 390 },
      { x: 360, y: 390 },
      { x: 360, y: 600 },
    ],
    distance: 15,
    estimatedTime: "15 sec",
  },
  {
    id: "2",
    fromRoom: "9", // Elevator
    toRoom: "2", // Computer Lab 2
    pathCoordinates: [
      { x: 190, y: 225 },
      { x: 190, y: 390 },
      { x: 620, y: 390 },
      { x: 620, y: 600 },
    ],
    distance: 30,
    estimatedTime: "25 sec",
  },
  {
    id: "3",
    fromRoom: "9", // Elevator
    toRoom: "3", // Computer Lab 3
    pathCoordinates: [
      { x: 190, y: 225 },
      { x: 190, y: 390 },
      { x: 870, y: 390 },
      { x: 870, y: 600 },
    ],
    distance: 45,
    estimatedTime: "40 sec",
  },
  {
    id: "4",
    fromRoom: "9", // Elevator
    toRoom: "4", // SOCI & Co-Curricular Office
    pathCoordinates: [
      { x: 190, y: 225 },
      { x: 190, y: 390 },
      { x: 848, y: 390 },
      { x: 848, y: 225 },
    ],
    distance: 45,
    estimatedTime: "40 sec",
  },
  {
    id: "5",
    fromRoom: "9", // Elevator
    toRoom: "5", // Stock Room
    pathCoordinates: [
      { x: 190, y: 225 },
      { x: 190, y: 390 },
      { x: 1050, y: 390 },
      { x: 1050, y: 225 },
    ],
    distance: 55,
    estimatedTime: "50 sec",
  },
  {
    id: "6",
    fromRoom: "9", // Elevator
    toRoom: "6", // PT Lab 1
    pathCoordinates: [
      { x: 190, y: 225 },
      { x: 190, y: 390 },
      { x: 1200, y: 390 },
      { x: 1200, y: 600 },
    ],
    distance: 65,
    estimatedTime: "55 sec",
  },
  {
    id: "7",
    fromRoom: "9", // Elevator
    toRoom: "7", // PT Lab 2
    pathCoordinates: [
      { x: 190, y: 225 },
      { x: 190, y: 390 },
      { x: 1700, y: 390 },
      { x: 1700, y: 600 },
    ],
    distance: 90,
    estimatedTime: "1 min 15 sec",
  },
  {
    id: "8",
    fromRoom: "9", // Elevator
    toRoom: "8", // PWD/Gender Neutral Comfort Room
    pathCoordinates: [
      { x: 190, y: 225 },
      { x: 190, y: 390 },
      { x: 1150, y: 390 },
      { x: 1150, y: 225 },
    ],
    distance: 60,
    estimatedTime: "50 sec",
  },
  {
    id: "9",
    fromRoom: "9", // Elevator
    toRoom: "10", // Computer Lab 4
    pathCoordinates: [
      { x: 190, y: 225 },
      { x: 190, y: 390 },
      { x: 1800, y: 390 },
      { x: 1800, y: 225 },
    ],
    distance: 100,
    estimatedTime: "1 min 25 sec",
  },
  {
    id: "10",
    fromRoom: "9", // Elevator
    toRoom: "11", // Comfort Room
    pathCoordinates: [
      { x: 190, y: 225 },
      { x: 190, y: 390 },
      { x: 1600, y: 390 },
      { x: 1600, y: 225 },
    ],
    distance: 85,
    estimatedTime: "1 min 10 sec",
  },
  // ── 2nd Floor Navigation Paths ──
  {
    id: "2f-nav-1",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-2", // Dean's Office 1
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 70, y: 480 },
      { x: 70, y: 740 },
    ],
    distance: 45,
    estimatedTime: "40 sec",
  },
  {
    id: "2f-nav-2",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-3", // Dean's Office 2
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 200, y: 480 },
      { x: 200, y: 790 },
    ],
    distance: 50,
    estimatedTime: "45 sec",
  },
  {
    id: "2f-nav-3",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-4", // Conference Room
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 300, y: 480 },
      { x: 300, y: 720 },
    ],
    distance: 40,
    estimatedTime: "35 sec",
  },
  {
    id: "2f-nav-4",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-5", // Printing Room
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 440, y: 480 },
      { x: 440, y: 710 },
    ],
    distance: 40,
    estimatedTime: "35 sec",
  },
  {
    id: "2f-nav-5",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-6", // Pantry
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 390, y: 480 },
      { x: 390, y: 800 },
    ],
    distance: 42,
    estimatedTime: "35 sec",
  },
  {
    id: "2f-nav-6",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-7", // Library
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 820, y: 480 },
      { x: 820, y: 600 },
    ],
    distance: 55,
    estimatedTime: "50 sec",
  },
  {
    id: "2f-nav-7",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-8", // Clinic
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 1250, y: 480 },
      { x: 1250, y: 600 },
    ],
    distance: 75,
    estimatedTime: "1 min 5 sec",
  },
  {
    id: "2f-nav-8",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-9", // IT Room
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 1400, y: 480 },
      { x: 1400, y: 600 },
    ],
    distance: 80,
    estimatedTime: "1 min 10 sec",
  },
  {
    id: "2f-nav-9",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-10", // Guidance Office
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 1400, y: 480 },
      { x: 1400, y: 730 },
    ],
    distance: 82,
    estimatedTime: "1 min 10 sec",
  },
  {
    id: "2f-nav-10",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-11", // Dean's Office 3
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 1550, y: 480 },
      { x: 1550, y: 750 },
    ],
    distance: 88,
    estimatedTime: "1 min 15 sec",
  },
  {
    id: "2f-nav-11",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-12", // Faculty Room
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 1579, y: 480 },
      { x: 1579, y: 614 },
    ],
    distance: 90,
    estimatedTime: "1 min 15 sec",
  },
  {
    id: "2f-nav-12",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-13", // Computer Lab 5
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 1700, y: 480 },
      { x: 1700, y: 450 },
    ],
    distance: 95,
    estimatedTime: "1 min 20 sec",
  },
  {
    id: "2f-nav-13",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-14", // Male Comfort Room
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 1500, y: 480 },
      { x: 1500, y: 317 },
    ],
    distance: 85,
    estimatedTime: "1 min 10 sec",
  },
  {
    id: "2f-nav-14",
    fromRoom: "2f-1", // Elevator
    toRoom: "2f-15", // Female Comfort Room
    pathCoordinates: [
      { x: 190, y: 320 },
      { x: 190, y: 480 },
      { x: 1500, y: 480 },
      { x: 1500, y: 427 },
    ],
    distance: 83,
    estimatedTime: "1 min 10 sec",
  },
  // ── 3rd Floor Navigation Paths ──
  {
    id: "3f-nav-1",
    fromRoom: "3f-1",
    toRoom: "3f-2",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 150, y: 550 },
      { x: 150, y: 740 },
    ],
    distance: 30,
    estimatedTime: "25 sec",
  },
  {
    id: "3f-nav-2",
    fromRoom: "3f-1",
    toRoom: "3f-3",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 420, y: 550 },
      { x: 420, y: 690 },
    ],
    distance: 35,
    estimatedTime: "30 sec",
  },
  {
    id: "3f-nav-3",
    fromRoom: "3f-1",
    toRoom: "3f-4",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 700, y: 550 },
      { x: 700, y: 690 },
    ],
    distance: 50,
    estimatedTime: "45 sec",
  },
  {
    id: "3f-nav-4",
    fromRoom: "3f-1",
    toRoom: "3f-5",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 950, y: 550 },
      { x: 950, y: 690 },
    ],
    distance: 60,
    estimatedTime: "50 sec",
  },
  {
    id: "3f-nav-5",
    fromRoom: "3f-1",
    toRoom: "3f-6",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 1100, y: 550 },
      { x: 1100, y: 690 },
    ],
    distance: 65,
    estimatedTime: "55 sec",
  },
  {
    id: "3f-nav-6",
    fromRoom: "3f-1",
    toRoom: "3f-7",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 1270, y: 550 },
      { x: 1270, y: 690 },
    ],
    distance: 72,
    estimatedTime: "1 min",
  },
  {
    id: "3f-nav-7",
    fromRoom: "3f-1",
    toRoom: "3f-8",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 1450, y: 550 },
      { x: 1450, y: 690 },
    ],
    distance: 80,
    estimatedTime: "1 min 10 sec",
  },
  {
    id: "3f-nav-8",
    fromRoom: "3f-1",
    toRoom: "3f-9",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 1570, y: 550 },
      { x: 1570, y: 690 },
    ],
    distance: 85,
    estimatedTime: "1 min 10 sec",
  },
  {
    id: "3f-nav-9",
    fromRoom: "3f-1",
    toRoom: "3f-10",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 1800, y: 550 },
      { x: 1800, y: 690 },
    ],
    distance: 100,
    estimatedTime: "1 min 25 sec",
  },
  {
    id: "3f-nav-10",
    fromRoom: "3f-1",
    toRoom: "3f-11",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 1750, y: 550 },
      { x: 1750, y: 400 },
    ],
    distance: 95,
    estimatedTime: "1 min 20 sec",
  },
  {
    id: "3f-nav-11",
    fromRoom: "3f-1",
    toRoom: "3f-12",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 1500, y: 550 },
      { x: 1500, y: 317 },
    ],
    distance: 85,
    estimatedTime: "1 min 10 sec",
  },
  {
    id: "3f-nav-12",
    fromRoom: "3f-1",
    toRoom: "3f-13",
    pathCoordinates: [
      { x: 230, y: 400 },
      { x: 230, y: 550 },
      { x: 1500, y: 550 },
      { x: 1500, y: 427 },
    ],
    distance: 83,
    estimatedTime: "1 min 10 sec",
  },
  // ── 4th Floor Navigation Paths ──
  {
    id: "4f-nav-1",
    fromRoom: "4f-1",
    toRoom: "4f-2",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 120, y: 550 },
      { x: 120, y: 740 },
    ],
    distance: 25,
    estimatedTime: "20 sec",
  },
  {
    id: "4f-nav-2",
    fromRoom: "4f-1",
    toRoom: "4f-3",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 350, y: 550 },
      { x: 350, y: 740 },
    ],
    distance: 35,
    estimatedTime: "30 sec",
  },
  {
    id: "4f-nav-3",
    fromRoom: "4f-1",
    toRoom: "4f-4",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 570, y: 550 },
      { x: 570, y: 740 },
    ],
    distance: 45,
    estimatedTime: "40 sec",
  },
  {
    id: "4f-nav-4",
    fromRoom: "4f-1",
    toRoom: "4f-5",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 800, y: 550 },
      { x: 800, y: 740 },
    ],
    distance: 55,
    estimatedTime: "50 sec",
  },
  {
    id: "4f-nav-5",
    fromRoom: "4f-1",
    toRoom: "4f-6",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 1050, y: 550 },
      { x: 1050, y: 740 },
    ],
    distance: 65,
    estimatedTime: "55 sec",
  },
  {
    id: "4f-nav-6",
    fromRoom: "4f-1",
    toRoom: "4f-7",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 1250, y: 550 },
      { x: 1250, y: 740 },
    ],
    distance: 75,
    estimatedTime: "1 min 5 sec",
  },
  {
    id: "4f-nav-7",
    fromRoom: "4f-1",
    toRoom: "4f-8",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 1430, y: 550 },
      { x: 1430, y: 740 },
    ],
    distance: 82,
    estimatedTime: "1 min 10 sec",
  },
  {
    id: "4f-nav-8",
    fromRoom: "4f-1",
    toRoom: "4f-9",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 1630, y: 550 },
      { x: 1630, y: 740 },
    ],
    distance: 92,
    estimatedTime: "1 min 20 sec",
  },
  {
    id: "4f-nav-9",
    fromRoom: "4f-1",
    toRoom: "4f-10",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 1830, y: 550 },
      { x: 1830, y: 740 },
    ],
    distance: 105,
    estimatedTime: "1 min 30 sec",
  },
  {
    id: "4f-nav-10",
    fromRoom: "4f-1",
    toRoom: "4f-11",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 1700, y: 550 },
      { x: 1700, y: 500 },
    ],
    distance: 95,
    estimatedTime: "1 min 20 sec",
  },
  {
    id: "4f-nav-11",
    fromRoom: "4f-1",
    toRoom: "4f-12",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 1500, y: 550 },
      { x: 1500, y: 317 },
    ],
    distance: 85,
    estimatedTime: "1 min 10 sec",
  },
  {
    id: "4f-nav-12",
    fromRoom: "4f-1",
    toRoom: "4f-13",
    pathCoordinates: [
      { x: 180, y: 420 },
      { x: 180, y: 550 },
      { x: 1500, y: 550 },
      { x: 1500, y: 427 },
    ],
    distance: 83,
    estimatedTime: "1 min 10 sec",
  },
  // ── 5th Floor Navigation Paths ──
  {
    id: "5f-nav-1",
    fromRoom: "5f-1",
    toRoom: "5f-2",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 150, y: 550 },
      { x: 150, y: 740 },
    ],
    distance: 30,
    estimatedTime: "25 sec",
  },
  {
    id: "5f-nav-2",
    fromRoom: "5f-1",
    toRoom: "5f-3",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 360, y: 550 },
      { x: 360, y: 740 },
    ],
    distance: 35,
    estimatedTime: "30 sec",
  },
  {
    id: "5f-nav-3",
    fromRoom: "5f-1",
    toRoom: "5f-4",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 600, y: 550 },
      { x: 600, y: 740 },
    ],
    distance: 45,
    estimatedTime: "40 sec",
  },
  {
    id: "5f-nav-4",
    fromRoom: "5f-1",
    toRoom: "5f-5",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 820, y: 550 },
      { x: 820, y: 740 },
    ],
    distance: 55,
    estimatedTime: "50 sec",
  },
  {
    id: "5f-nav-5",
    fromRoom: "5f-1",
    toRoom: "5f-6",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 1050, y: 550 },
      { x: 1050, y: 740 },
    ],
    distance: 65,
    estimatedTime: "55 sec",
  },
  {
    id: "5f-nav-6",
    fromRoom: "5f-1",
    toRoom: "5f-7",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 1250, y: 550 },
      { x: 1250, y: 740 },
    ],
    distance: 75,
    estimatedTime: "1 min 5 sec",
  },
  {
    id: "5f-nav-7",
    fromRoom: "5f-1",
    toRoom: "5f-8",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 1400, y: 550 },
      { x: 1400, y: 740 },
    ],
    distance: 80,
    estimatedTime: "1 min 10 sec",
  },
  {
    id: "5f-nav-8",
    fromRoom: "5f-1",
    toRoom: "5f-9",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 1550, y: 550 },
      { x: 1550, y: 740 },
    ],
    distance: 88,
    estimatedTime: "1 min 15 sec",
  },
  {
    id: "5f-nav-9",
    fromRoom: "5f-1",
    toRoom: "5f-10",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 1750, y: 550 },
      { x: 1750, y: 740 },
    ],
    distance: 100,
    estimatedTime: "1 min 25 sec",
  },
  {
    id: "5f-nav-10",
    fromRoom: "5f-1",
    toRoom: "5f-11",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 1750, y: 550 },
      { x: 1750, y: 400 },
    ],
    distance: 98,
    estimatedTime: "1 min 20 sec",
  },
  {
    id: "5f-nav-11",
    fromRoom: "5f-1",
    toRoom: "5f-12",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 1500, y: 550 },
      { x: 1500, y: 317 },
    ],
    distance: 85,
    estimatedTime: "1 min 10 sec",
  },
  {
    id: "5f-nav-12",
    fromRoom: "5f-1",
    toRoom: "5f-13",
    pathCoordinates: [
      { x: 190, y: 420 },
      { x: 190, y: 550 },
      { x: 1500, y: 550 },
      { x: 1500, y: 427 },
    ],
    distance: 83,
    estimatedTime: "1 min 10 sec",
  },
]

export const schedules: ClassSchedule[] = [
  // Computer Lab 1 schedules
  {
    id: "s1",
    roomId: "1",
    subjectName: "Web Development",
    subjectCode: "IT301",
    facultyName: "Prof. Antonio Ebrado Jr.",
    dayOfWeek: "Monday",
    startTime: "08:00",
    endTime: "09:30",
    section: "BSIT-3A",
  },
  {
    id: "s2",
    roomId: "1",
    subjectName: "Web Development",
    subjectCode: "IT301",
    facultyName: "Prof. Antonio Ebrado Jr.",
    dayOfWeek: "Wednesday",
    startTime: "08:00",
    endTime: "09:30",
    section: "BSIT-3A",
  },
  {
    id: "s3",
    roomId: "1",
    subjectName: "Database Management",
    subjectCode: "IT202",
    facultyName: "Prof. Antonio Ebrado Jr.",
    dayOfWeek: "Tuesday",
    startTime: "10:00",
    endTime: "11:30",
    section: "BSIT-2A",
  },
  {
    id: "s4",
    roomId: "1",
    subjectName: "Database Management",
    subjectCode: "IT202",
    facultyName: "Prof. Antonio Ebrado Jr.",
    dayOfWeek: "Thursday",
    startTime: "10:00",
    endTime: "11:30",
    section: "BSIT-2A",
  },
  {
    id: "s5",
    roomId: "1",
    subjectName: "Introduction to Computing",
    subjectCode: "IT101",
    facultyName: "Prof. Maria Santos",
    dayOfWeek: "Monday",
    startTime: "13:00",
    endTime: "14:30",
    section: "BSIT-1A",
  },
  {
    id: "s6",
    roomId: "1",
    subjectName: "Introduction to Computing",
    subjectCode: "IT101",
    facultyName: "Prof. Maria Santos",
    dayOfWeek: "Wednesday",
    startTime: "13:00",
    endTime: "14:30",
    section: "BSIT-1A",
  },
  // Computer Lab 2 schedules
  {
    id: "s7",
    roomId: "2",
    subjectName: "Object-Oriented Programming",
    subjectCode: "IT201",
    facultyName: "Prof. Maria Santos",
    dayOfWeek: "Monday",
    startTime: "08:00",
    endTime: "09:30",
    section: "BSIT-2B",
  },
  {
    id: "s8",
    roomId: "2",
    subjectName: "Object-Oriented Programming",
    subjectCode: "IT201",
    facultyName: "Prof. Maria Santos",
    dayOfWeek: "Wednesday",
    startTime: "08:00",
    endTime: "09:30",
    section: "BSIT-2B",
  },
  {
    id: "s9",
    roomId: "2",
    subjectName: "Data Structures and Algorithms",
    subjectCode: "IT203",
    facultyName: "Prof. Ricardo Delos Reyes",
    dayOfWeek: "Tuesday",
    startTime: "08:00",
    endTime: "09:30",
    section: "BSIT-2A",
  },
  {
    id: "s10",
    roomId: "2",
    subjectName: "Data Structures and Algorithms",
    subjectCode: "IT203",
    facultyName: "Prof. Ricardo Delos Reyes",
    dayOfWeek: "Thursday",
    startTime: "08:00",
    endTime: "09:30",
    section: "BSIT-2A",
  },
  {
    id: "s11",
    roomId: "2",
    subjectName: "Networking Fundamentals",
    subjectCode: "IT302",
    facultyName: "Dr. Jose Mendoza",
    dayOfWeek: "Monday",
    startTime: "10:00",
    endTime: "11:30",
    section: "BSIT-3B",
  },
  {
    id: "s12",
    roomId: "2",
    subjectName: "Networking Fundamentals",
    subjectCode: "IT302",
    facultyName: "Dr. Jose Mendoza",
    dayOfWeek: "Wednesday",
    startTime: "10:00",
    endTime: "11:30",
    section: "BSIT-3B",
  },
  // Computer Lab 3 schedules
  {
    id: "s13",
    roomId: "3",
    subjectName: "Software Engineering",
    subjectCode: "IT303",
    facultyName: "Prof. Ricardo Delos Reyes",
    dayOfWeek: "Monday",
    startTime: "08:00",
    endTime: "09:30",
    section: "BSIT-3A",
  },
  {
    id: "s14",
    roomId: "3",
    subjectName: "Software Engineering",
    subjectCode: "IT303",
    facultyName: "Prof. Ricardo Delos Reyes",
    dayOfWeek: "Wednesday",
    startTime: "08:00",
    endTime: "09:30",
    section: "BSIT-3A",
  },
  {
    id: "s15",
    roomId: "3",
    subjectName: "Systems Analysis and Design",
    subjectCode: "IT304",
    facultyName: "Prof. Elena Garcia",
    dayOfWeek: "Tuesday",
    startTime: "13:00",
    endTime: "14:30",
    section: "BSIT-3B",
  },
  {
    id: "s16",
    roomId: "3",
    subjectName: "Systems Analysis and Design",
    subjectCode: "IT304",
    facultyName: "Prof. Elena Garcia",
    dayOfWeek: "Thursday",
    startTime: "13:00",
    endTime: "14:30",
    section: "BSIT-3B",
  },
  {
    id: "s17",
    roomId: "3",
    subjectName: "Human-Computer Interaction",
    subjectCode: "IT305",
    facultyName: "Prof. Maria Santos",
    dayOfWeek: "Friday",
    startTime: "08:00",
    endTime: "11:00",
    section: "BSIT-3A",
  },
  {
    id: "s18",
    roomId: "3",
    subjectName: "Capstone Project 1",
    subjectCode: "IT401",
    facultyName: "Prof. Antonio Ebrado Jr.",
    dayOfWeek: "Saturday",
    startTime: "08:00",
    endTime: "11:00",
    section: "BSIT-4A",
  },
]
